//  Define the Permission Matrix based on the image
export const ROLE_PERMISSIONS = {
  "Super Admin": {
    Dashboard: "Full",
    Orders: "Full",
    Vendors: "Full",
    Products: "Full",
    Users: "Full",
    Payments: "Full",
    Payouts: "Full",
    Logistics: "Full",
    Support: "Full",
    Marketing: "Full",
    Blogs: "Full",
    Settings: "Full",
  },
  Ops: {
    Dashboard: "View",
    Orders: "Full",
    Vendors: "Full",
    Products: "Full",
    Users: "Full",
    Payments: "No",
    Payouts: "No",
    Logistics: "View",
    Support: "View",
    Marketing: "View",
    Blogs: "View",
    Settings: "No",
  },
  Finance: {
    Dashboard: "View",
    Orders: "View",
    Vendors: "View",
    Products: "View",
    Users: "View",
    Payments: "Full",
    Payouts: "Full",
    Logistics: "No",
    Support: "No",
    Marketing: "No",
    Blogs: "View",
    Settings: "No",
  },
  Logistics: {
    Dashboard: "View",
    Orders: "View",
    Vendors: "No",
    Products: "View",
    Users: "View",
    Payments: "No",
    Payouts: "No",
    Logistics: "Full",
    Support: "No",
    Marketing: "No",
    Blogs: "View",
    Settings: "No",
  },
  Support: {
    Dashboard: "View",
    Orders: "View",
    Vendors: "View",
    Products: "View",
    Users: "View",
    Payments: "No",
    Payouts: "No",
    Logistics: "No",
    Support: "Full",
    Marketing: "No",
    Blogs: "View",
    Settings: "No",
  },
  "Read-Only": {
    Dashboard: "View",
    Orders: "View",
    Vendors: "View",
    Products: "View",
    Users: "View",
    Payments: "View",
    Payouts: "View",
    Logistics: "View",
    Support: "View",
    Marketing: "View",
    Blogs: "View",
    Settings: "No",
  },
};
